### ISSUE TITLE
no build folder created after npm run build

### ISSUE THREAD

**Issue by mahmoud305** [chetanverma16/react-portfolio-template#27]
when i run npm run build it executes successfully but no build folder created
![error](https://user-images.githubusercontent.com/61843121/138573527-a5ca94b8-765c-4ca7-8e20-7ec77150cbaf.PNG)
 the screenshot for executing npm run deploy command.

i want to deploy the portfolio to git hub pages but that what happen (no build folder generated )
link for the compressed code [code] (https://www.mediafire.com/file/qzl4rb68tj53qa6/react-portfolio-template-master.rar/file)

**Comment by ArjunaAcchaDipa** [comment]
Hey, I'm facing the same problem yesterday. But you can take a look at this [youtube video](https://youtu.be/8tz9zDmrEbA) to solve it. The reason why npm run deploy command doesn't work is because the code is using Gatsby and to host it, it needs some settings.

**Comment by caramelmelmel** [comment]
yes! what i did was to write a gatsby config command like a bash script to deploy!
