### ISSUE TITLE
Blog index page responsive

### ISSUE THREAD

**Issue by Aryan3212** [chetanverma16/react-portfolio-template#43]
Hi Chetan!

I want to make a pull request that addresses a responsiveness issue on the blogs index page. The fixed size of the entries meant that they overlapped on each other if the screen was small. I think using a flexbox would address this issue effectively unless you have other design considerations for using grids.

Before: 
![image](https://user-images.githubusercontent.com/57558971/176842837-87a2469b-2aaf-47c3-b16c-a6d917448a34.png)

I really loved the design of your portfolio(the previous version) and forked so I could use it for myself.

**Comment by chetanverma16** [comment]
Yes, please that would be a great help!!
