### ISSUE TITLE
Add a very simple navbar to the mobile view

### ISSUE THREAD

**Issue by Aryan3212** [chetanverma16/react-portfolio-template#45]
I was hoping to create a navbar as done on my fork of the project but which is larger making it more accessible.

Something like the image below, but with better demarcations and accessibility. We aren't using any icon pack and the one on the image was made using a raw SVG path. Maybe we can just have a button instead of the "hamburger+menu". 

![image](https://user-images.githubusercontent.com/57558971/177462145-fedea763-6503-4835-b642-022df9f3eecb.png)

**Comment by sanjayk0508** [comment]
Hey Aryan, i can work on this issue. I'm well versed with react. And i'm pretty new to open source.

PROBLEM: I cloned the repo in local IDE, I couldn't run the website after doing 'npm start'. It shows something like this-
> react-portfolio-template@0.1.0 start
> next start

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error: Could not find a production build in the 'C:\Users\Admin\OneDrive\Desktop\Open source\navbar\react-portfolio-template\.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (C:\Users\Admin\OneDrive\Desktop\Open source\navbar\react-portfolio-template\node_modules\next\dist\server\next-server.js:137:23)
    at new Server (C:\Users\Admin\OneDrive\Desktop\Open source\navbar\react-portfolio-template\node_modules\next\dist\server\base-server.js:93:29)
    at new NextNodeServer (C:\Users\Admin\OneDrive\Desktop\Open source\navbar\react-portfolio-template\node_modules\next\dist\server\next-server.js:86:9)     
    at NextServer.createServer (C:\Users\Admin\OneDrive\Desktop\Open source\navbar\react-portfolio-template\node_modules\next\dist\server\next.js:109:16)     
    at async C:\Users\Admin\OneDrive\Desktop\Open source\navbar\react-portfolio-template\node_modules\next\dist\server\next.js:121:31
PS C:\Users\Admin\OneDrive\Desktop\Open source\navbar\react-portfolio-template> 

I'm willing to contribute and learn, so pls help out in this issue.

**Comment by Aryan3212** [comment]
You should run the 'yarn dev' command. I'm not sure what npm start does since I didn't see the command but maybe it spins uo the production build which first needs to be built using 'next build'. Ask away for any questions.

**Comment by sanjayk0508** [comment]
Ran yarn dev and shows like this-
yarn dev
yarn run v1.22.18
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
wait  - compiling...
event - compiled client and server successfully in 1336 ms (126 modules)

**Comment by sanjayk0508** [comment]
Thanks, It worked :)

**Comment by chetanverma16** [comment]
Hey guys,
anyone working on this issue!!

**Comment by sanjayk0508** [comment]
yes, i'm working on it

**Comment by Aryan3212** [comment]
Is this issue still open?

**Comment by chetanverma16** [comment]
Yeah,
this one is still open!!
I am not sure if anyone is working on it!
