### ISSUE TITLE
Overall responsiveness

### ISSUE THREAD

**Issue by Aryan3212** [chetanverma16/react-portfolio-template#59]
This just sprang up in my mind but changing tailwind CSS's config for mob to 0px would make most things automatically responsive. The current settings cause things to break below 360px. Also we could remove the mob: prefix altogether from everywhere including the config file.

**Comment by Aryan3212** [comment]
I'm working on this, we can review the PR and decide whether it's alright.

**Comment by chetanverma16** [comment]
Yeah,
Removing the Mob makes sense.
I am looking forward to your PR.

**Comment by chetanverma16** [comment]
Nice One!
Merged 🚀
