### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by chetanverma16** [chetanverma16/react-portfolio-template#63]

**Comment by chetanverma16** [comment]
Hey,
@GAbdulWahab sure 
shall I assign it to you?

**Comment by GAbdulWahab** [comment]
@chetanverma16 
sure  in the days coming i will work for it

**Comment by GAbdulWahab** [comment]
@chetanverma16  am sorry I think my level   is a beginner and I didn't learn to react until now
