### ISSUE TITLE
i have issue in running the site 

### ISSUE THREAD

**Issue by Collins87mbathi** [chetanverma16/react-portfolio-template#67]
![next](https://user-images.githubusercontent.com/74602469/181942975-ead0bfb1-779e-49c1-8ef8-8f2ab28deb12.PNG)

**Comment by chetanverma16** [comment]
Hey @Collins87mbathi,
can you try removing `package-lock.json` and `yarn.lock`
and try again?

**Comment by chetanverma16** [comment]
No updates! on this 
so closing this issue
