### ISSUE TITLE
Blog showing when typing in the url

### ISSUE THREAD

**Issue by achu-krishna** [chetanverma16/react-portfolio-template#68]
Hi nice job! Just a question, if someone were to put in /blog after the URL, wouldn't the route still exist? We are only removing the button here. Maybe we can work on this enhancement later. A very minor issue tbh, great work on the commit 😄

_Originally posted by @Aryan3212 in https://github.com/chetanverma16/react-portfolio-template/issues/50#issuecomment-1180204152_

**Comment by chetanverma16** [comment]
Yeah,
awesome work thanks for the PR!
