### ISSUE TITLE
Layout broken

### ISSUE THREAD

**Issue by Ladvace** [chetanverma16/react-portfolio-template#8]
I was looking at the preview but it looks like this.

Browser: mozilla firefox

![immagine](https://user-images.githubusercontent.com/31326058/88374015-37ea1700-cd99-11ea-98a2-f2d0d6f44db3.png)

**Comment by 007surajsinghnegi** [comment]
no man i previewed it on mozilla and chrome both it works great

**Comment by DavideVito** [comment]
> I was looking at the preview but it looks like this.
> 
> Browser: mozilla firefox
> 
> ![immagine](https://user-images.githubusercontent.com/31326058/88374015-37ea1700-cd99-11ea-98a2-f2d0d6f44db3.png)

same here

**Comment by raiyansarker** [comment]
I am also having the issue! You should look into it again!
