### ISSUE TITLE
List of major ui problems in the template

### ISSUE THREAD

**Issue by sanjayk0508** [chetanverma16/react-portfolio-template#91]
1. While scrolling the page The "Edit Data" button, the button gets hided behind the WorkCard component.
![Screenshot (44)](https://user-images.githubusercontent.com/102804548/189498254-5c75f89b-4569-4af1-9b92-dfe04cec8b68.png)

2.  The Dashboard component inside /edit is getting mixed up / hiding the labels and inputs.
![Screenshot (45)](https://user-images.githubusercontent.com/102804548/189499385-4afeac51-9f85-433e-b4dc-7fe1d9734fd5.png)

I will try and resolve this issues.

**Comment by chetanverma16** [comment]
Thanks for these bug reports,
Dark Mode has some major problems.

**Comment by sanjayk0508** [comment]
Hey Chetan, I sent a pull request which resolves those bugs. Just review the PR and let me know if any changes are needed or else give your feedback on it.
